### ISSUE TITLE
runit issues with Docker

### ISSUE THREAD

**Issue by jcejohnson** [opscode-cookbooks/jenkins#368] opened 2015-05-31 15:42 UTC
I've been trying to get this to work with Docker but the jenkins_jnlp_slave consistently fails with the error:
```
warning: /etc/service/jenkins-slave: unable to open supervise/ok: file does not exist
```
I have a [sample project](https://github.com/jcejohnson/chef-notes/tree/master/jenkins-cookbook) using Test Kitchen and Kitchen::Docker. I added a test fixture to explicitly launch runsvdir but that didn't solve the problem. The [runit section of the README](https://github.com/jcejohnson/chef-notes/tree/master/jenkins-cookbook#runit) goes into a bit more detail.

Interestingly, with the test fixture in place, running _kitchen converge_ a second time is successful. There seems to be something that happens in the 1st converge during or after jenkins_jnlp_slave that makes the 2nd converge work.

My metadata.rb dependencies:
  depends "jenkins", "~> 2.3.1"
  depends "runit", "~> 1.5"

My Test Kitchen target is:
- boot2docker 1.6.2
- Virtualbox 4.3.28
- WIndows 8.1 host
- CentOS 6.6 and Ubuntu 14.04 images

CentOS 6.6 is my production target for both host and container.

**Comment by schisamo** [comment] 2015-09-01 13:16
This is a dupe of https://github.com/opscode-cookbooks/jenkins/issues/205.

**Closed by schisamo** 2015-09-01 13:16 UTC
